# Site Settings
name: AZTemi
url: www.aztemi.com
timezone: UTC
disqus_shortname:
google_analytics: UA-144765452-1
github: https://github.com/t4top/

# feeds
feed:
  rss: /rss.xml
  atom: /atom.xml

# languages support
# Use only ISO 639-1 Language Codes (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
default_language: en
fallback_language: en
supported_languages:
  - en
  - bg
  - de
  - ja
